# 问题：影响芒草产量的候选基因

## 预处理

### 株高是否可以代表生物量

```r
JH.0=lm(JH.biomass~JH.height-1) #使用-1来删除截距项
summary(JH.0)
plot(JH.height,JH.biomass,xlim=c(0,400))
abline(JH.0)

QG.0=lm(QG.biomass~QG.height-1)
summary(QG.0)
plot(QG.height,QG.biomass,xlim=c(0,450))
abline(QG.0)
```

## 相关分析

### 株高和某个基因表达量的图示

```r
x # 26个个体的株高
y # 26个个体的某个基因表达量
xhist <- hist(x, plot = FALSE)
yhist <- hist(y, plot = FALSE)
top <- max(c(xhist$counts, yhist$counts))
xrange <- c(min(x),max(x))
yrange <- c(min(y),max(y))
nf <- layout(matrix(c(2,0,1,3),2,2,byrow = TRUE), c(3,1), c(1,3), TRUE)
layout.show(nf)

par(mar = c(3,3,1,1))
plot(x, y, xlim = xrange, ylim = yrange, xlab = "", ylab = "")
par(mar = c(0,3,1,1))
barplot(xhist$counts, axes = FALSE, ylim = c(0, top), space = 0)
par(mar = c(3,0,1,1))
barplot(yhist$counts, axes = FALSE, xlim = c(0, top), space = 0, horiz = TRUE)
```

### 简单相关

####非参数方法Spearman和Kendall
```r
i=1
for (i in 1:260)
{
    ct=cor.test(Height,gene[,i],method="spearman") #之前经过shapiro.test没有找到表达量符合正态分布的基因
    if (ct$p.value<0.05)  print(names(gene)[i])
}
```

用上述代码分别进行了Spearman和Kendall秩相关分析，Spearman方法结果如下：  
p<0.01水平：Gene 62.  
p<0.05水平：Gene 34, 65, 77, 88, 146, 171, 195, 251, 260.  
Kendall相关只多出一个p=0.0496的Gene 13，其他基因与Spearman相关都相同。  
以上，共输出11个基因，没有做JH和QG两地数据的分别筛选。  
这里存在一个ties的问题，会导致非参数方法Spearman/Kendall的效果变差。

####Goodman-Kruskal方法
由于Spearman/Kendall方法中ties的影响，引入Goodman-Kruskal方法。  
但是，Goodman-Kruskal方法是对分类变量使用的，因此需要进行数据的转换，在这个过程中会损失一部分信息。  
```r
library(GoodmanKruskal)
attach(w)
GKtau(Height,Gene1)
   xName yName Nx Ny tauxy tauyx
1 Height Gene1 21 17 0.903 0.703
```
Nx和Ny分别代表Height和Gene1分别有多少个水平（视作分类变量）。另外可以看到输出中并没有给出p值。  
根据该程序包的说明：  
> 　　The Goodman and Kruskal tau measure is an **asymmetric** association measure between two categorical variables, based on the extent to which variation in one variable can be explained by the other.

由于我们希望了解Gene对Height的影响，因此这里应该关注tauyx。
```r
for (i in 1:260)
{
    GK=GKtau(Height,gene[,i])
    if (GK$tauyx>=0.9)  print(names(gene)[i])
}
```
tauyx≥0.95：Gene 168, 219, 227, 248.  
tauyx≥0.9：Gene 137, 153, 159, 169, 210, 212, 218, 224, 228, 233, 245, 246.  
即使设定在tauyx≥0.9水平，也输出了很多基因（共16个）。但上面分析时没有统一Height和Gene的level个数一致，不知道对结果会不会有影响，因此进行下一步验证。  
Gene表达量数据由于0比较多，level都少于Height。  
```r
for (i in 1:260)
    gene.ca[,i]=as.ordered(gene[,i]) #将Gene转换为有序变量

for (i in 1:260)
{
    Height.ca=Height
    level.num=length(unique(gene.ca[,i])) #去重后统计该基因表达量有多少个不同值，即多少个不同水平。
    Height.ca=GroupNumeric(Height, n=level.num, orderedFactor=TRUE)
    #GroupNumeric为GK包中的函数，用n=level.num限定Height的水平个数与该基因相同，orderedFactor=TRUE有序变量。
    GK=GKtau(Height.ca,gene.ca[,i])
    if (GK$tauyx>=0.9)  print(names(gene.ca)[i])
}
```
输出结果与不统一level时完全一致。  
多次检查确认方法的执行并无问题。所以，这个方法得出的结果就是非常奇怪……  

####Spearman, Kendall和Goodman-Kruskal方法的一点比较

在网上查到的一些解释如下，来自Cross Validated（不知道靠不靠谱？）：  
> 　　Spearman is used in place of usual linear correlations, and that Kendall-Tau is less direct and more closely resembles Goodman-Kruskal Gamma.  
> 　　**Spearman rho vs Kendall tau.** These two are so much computationally different that you *cannot* directly compare their magnitudes. Spearman is usually higher by 1/4 to 1/3 and this makes one incorrectly conclude that Spearman is “better” for a particular dataset. The difference between rho and tau is in their ideology, proportion-of-variance for rho and probability for tau.  
> 　　Rho is a usual Pearson r applied for ranked data, and like r, is **more sensitive to points with large moments** (that is, deviations from cloud centre) than to points with small moments. Tau is an extension of Gamma and is **equally sensitive to all the data points**, so it is less sensitive to peculiarities in shape of the ranked cloud.  
> 　　Tau is more “general” than rho, for rho is warranted only when you believe the underlying (model, or functional in population) relationship between the variables is **strictly monotonic**. While Tau allows for nonmonotonic underlying curve and measures which monotonic “trend”, positive or negative, prevails there overall. Rho is comparable with r in magnitude; tau is not.  
> 　　**Kendall tau as Gamma**. Tau is just a standardized form of Gamma. Several related measures all have numerator P−Q but differ in normalizing *denominator*.  

我们的数据极值点比较多，而Spearman对极值点更为敏感，所以有可能会倾向于得出更大的rho（假相关？）。另外，Spearman方法更适用于（要求？）两个变量是单调线性相关的。因此，Kendall和Goodman-Kruskal这样更“general”的方法也许更合适。  

### 回归分析
以下使用的两种回归分析都在mblm程序包中，使用同一个函数mblm( )。  
其中若设定repeated=FALSE，则“a single median estimators are calculated”，对应Theil-Sen single median method；若设定repeated=TRUE (default)，则对应Siegel repeated medians.  
根据mblm程序包说明：  
> 　　The breakdown point of Theil-Sen method is about 29%, Siegel extended it to 50%, so these regression methods are very robust. Additionally, if the errors are normally distributed and no outliers are present, the estimators are very similar to classic least squares.

其中breakdown point的定义和一些说明如下（据Wikipedia）：  
> 　　The breakdown point of an estimator is the proportion of incorrect observations (e.g. arbitrarily large observations) an estimator can handle before giving an incorrect (e.g. arbitrarily large) result.  
> 　　Intuitively, we can understand that a breakdown point cannot exceed 50% because if more than half of the observations are contaminated, it is not possible to distinguish between the underlying distribution and the contaminating distribution. Therefore, the maximum breakdown point is 0.5 and there are estimators which achieve such a breakdown point. For example, the median has a breakdown point of 0.5.

这两种回归方法都非常稳健，因此应该比普通的最小二乘回归更适合处理株高—表达量这样离群点多、variation大的数据。  

#### 非参数回归Theil
```r
Height=w[,2] #株高
g=NULL
library(mblm)

for (i in 1:260)
{
    g=gene.all[,i]
    #如果直接在mblm函数中写Height~gene.all[,i]，会报错Error in order(x) : argument 1 is not a vector.
    theil=summary(mblm(Height~g,repeated=FALSE))
    #如果不套一层summary( )，直接用mblm对象$coefficients只输出斜率和截距，没有p值.
    p.value=theil$coefficients[2,4] #“H0: 斜率为0”的wilcox.test得到.
    if (p.value<5e-06)  print(names(gene.all)[i])
}
```
感觉Theil回归得到的p值普遍都很小，即使筛选条件设为p<5×10^-6，还是能输出14个基因：  
Gene 12, 13, 34, 62, 65, 77, 123, 130, 146, 163, 171, 195, 215, 260.  
不过，这些基因里还是有较多都是和其他方法结果一致的。  

#### 稳健回归Siegel

```r
for (i in 1:260)
{
    g=gene.all[,i]
    siegel=summary(mblm(Height~g,repeated=TRUE))
    p.value=siegel$coefficients[2,4]
    if (p.value<0.001)  print(names(gene.all)[i])
}
```
代码基本同Theil回归，只是改了repeated为TRUE，筛选条件设为p<0.001，输出16个基因：  
Gene 12, 13, 23, 34, 53, 62, 65, 77, 123, 146, 163, 195, 215, 222, 246, 251.

### 矩阵相关

#### 剔除FPKM中位数为0的基因

```r
i=1
while (i<=260) #使用for语句则默认每次循环后i++，会绕过后面else i=i+1的设定
{
   if (i>ncol(gene))  break #否则在删去一些列后i过大可能会报错“undefined column selected”
    else if (median(gene[,i])==0)  gene=gene[c(-i)] #删去FPKM值中位数为0的列
    else i=i+1 #若第a列被删去，原第a+1列会补上来，若直接i++会使原第a+1列不经检验就跳过
}
```
#### 建立矩阵

```r
a=NULL #用于暂存后面相除得到的数值
x=y=z=1 #依次代表JH、QG、Gene下标

while(z<=235) #剔除后剩下235个基因
{
    while(x<=12)
    {
        while(y<=12)
        {
            a=c(a,gene[y+12,z]/gene[x,z]) #固定Gene和JH下标，用QG1~12作分子相除
            y=y+1
        }
        x=x+1 #JH下标+1
        y=1 #为了接下来能够重新运行while(y<=12)循环
    }
    z=z+1 #Gene下标+1
    x=1
}
```
使用max()查找到相除值中最大值为12537.33，故将极值Inf替换为1×10^6（高2个数量级），NaN替换为0.
```r
a=as.character(a)
a=sub("NaN","0",a,fixed=TRUE)
a=sub("Inf","1000000",a,fixed=TRUE)
a=as.numeric(a)
```
再用此时的a建立表达量矩阵.
```r
dim1=c("QG1","QG2","QG3","QG4","QG5","QG6","QG7","QG8","QG9","QG10","QG11","QG12")
dim2=sub("QG","JH",dim1,fixed=TRUE) #dim1为RowNames，dim2为ColNames
dim3=names(gene)

gene.matrix=array(a,c(12,12,235),dimnames=list(dim1,dim2,dim3))
```
用相似方法建立株高矩阵.  

#### 矩阵相关分析

```r
library(vegan)
order=sig=corr=NULL #分别用来暂存找到的基因编号、p值和相关系数
i=1
while(i<=235)
{
    man=mantel(height.matrix,gene.matrix[,,i],method="spearman",permutations=10000)
    sig=c(sig,man$signif)
    corr=c(corr,man$statistic)
    if (man$signif<0.05)  order=c(order,i)
    i=i+1
}
print(dim3[order])
[1] "Gene40"  "Gene65"  "Gene95"  "Gene177" "Gene195" "Gene206" "Gene257"
print(sig[order])
[1] 0.01509849 0.03999600 0.00659934 0.02999700 0.02739726 0.02629737 0.04739526
print(corr[order])
[1] 0.4114945 0.3663900 0.4705826 0.3443132 0.3816398 0.3461605 0.3007196
```
p<0.01水平：Gene 95.  
p<0.05水平：Gene 40, 65, 177, 195, 206, 257.  
共7个基因，其相关系数都在0.3-0.5左右.  
矩阵相关要求中位数大于0，这样确实会损失一部分信息。为了考察其影响，用所有基因的数据按上述方法做了一遍矩阵相关，找到2个中位数为0但置换检验显著的基因，为Gene171和222，其置换检验p值分别为0.00859828和0.04539092，相关系数为0.4771875和0.3017154。  
_**Update**_：用median()输出看了一下，Gene171的中位数确实为0没错，但Gene222中位数不为0，只是p值比较接近0.05，第一次置换检验中可能恰好没有被筛选出来。

### 机器学习

####数据下标的划分  
```r
n=24 #观测值个数，即南荻个体数
Z=5 #交叉验证的折数
zz1=1:n #zz1为所有观测值的下标
zz2=rep(1:Z,ceiling(n/Z))[1:n]
zz2=sample(zz2,n) #zz2为1:5的随机排列
```
####随机森林回归和交叉验证
```r
for (i in 1:Z)
{
    m=zz1[zz2==i] #把数据随机地分成5份，取其中1份作为测试集，其余4份为训练集.
    RF=randomForest(Height~.,data=w[-m,],mtry=100,ntree=10000)
    #用训练集建立模型，mtry是number of predictors sampled for spliting at each node，默认是自变量数/3.
    y0=predict(RF,w[-m,]) #对训练集的预测.
    y1=predict(RF,w[m,]) #对测试集的预测.
    NMSE0[i]=mean((w[-m,2]-y0)^2)/mean((w[-m,2]-mean(w[-m,2]))^2)
    NMSE[i]=mean((w[m,2]-y1)^2)/mean((w[m,2]-mean(w[m,2]))^2)
} #对训练集和测试集分别得到5个标准化均方误差（NMSE），根据其公式定义看应该是均方误差除以方差得到.
(mean(NMSE0)) #输出训练集5次平均的NMSE
(mean(NMSE)) #测试集
```
反复试了几次，交叉验证的结果还是都不太好，划分5折训练集的NMSE在0.18左右，测试集的NMSE一直大于1。  
尝试增加了函数中的mtry和ntree改进不大（后来上网查了一下，有人说默认的mtry一般不用改，往往都是加tree的数量，在精度和运算时间中权衡），倒是几次重新抽样建立5个集对结果的影响不小，NMSE从1.95到1.37都有。  
因为自变量个数远大于观测值个数，感觉回归拟合时最终得到什么样的方程是较为不确定的，在很大程度上取决于用哪一部分数据建立模型；另外如果“抽样没抽好”，就会看到有某一个集做测试集时NMSE极大，从而得出很大的NMSE平均值。可能这就是为什么重新sample建立5个集对结果的影响会比较大，而且再增加tree的数量能改善的也有限。  
有点茫然，不是很清楚怎么去调整改进。  
_**Update**_：用上全部数据回归后，测试集的NMSE可以<1了。  

####给出变量重要性
```r
RF=randomForest(Height~.,data=w,mtry=100,ntree=10000,importance=TRUE,importanceSD=T)
imSD=sort(RF$importanceSD,decreasing=TRUE) #从置换检验的标准误差角度给出变量重要性
imAccu=sort(RF$importance[,1],decreasing=TRUE) #从预测精度角度给出
imMSE=sort(RF$importance[,2],decreasing=TRUE) #从均方误差角度给出

(imSD[1:10])
   Gene62   Gene195    Gene72    Gene94   Gene260    Gene88    Gene77    Gene14    Gene43   Gene214
16.082090 12.188445 10.931648 10.769899  9.823089  8.958934  8.673335  8.377055  8.249838  8.190552
 
(imAccu[1:10])
   Gene62   Gene195    Gene88   Gene260   Gene171    Gene77   Gene117    Gene14    Gene44    Gene34 
301.46258 109.54764  60.59024  60.09107  52.19416  41.05383  34.45220  29.15351  19.75451  14.06321 
 
(imMSE[1:10])
   Gene62   Gene195   Gene214    Gene72    Gene77   Gene260    Gene88    Gene94    Gene14   Gene171 
 9862.699  5675.353  3745.121  3672.607  3551.497  3437.481  3040.673  2736.628  2673.034  2654.348 
```
共筛选出14个基因：Gene 14, 34, 43, 44, 62, 72, 77, 88, 94, 117, 171, 195, 214, 260.  

####对表达量数据取常用对数
由于NMSE是以均值为基准去比较，而转录组数据variation太大，因此考虑对表达量取对数再试一试。  
```r
w1=w #w为实验地+株高+260个基因表达量数据，共262个变量
x=1;y=3

while (y<=262) #第y列，从3开始是要略过Reigion和Height不处理
{
    while (x<=24) #第x行
    {
        if (w1[x,y]==0)  w1[x,y]=1e-06 #用小值替换0以取对数
        x=x+1
    }
    y=y+1
    x=1
}

for (i in 3:262)
    w1[,i]=log10(w1[,i])
```
此后的随机森林回归和交叉验证同上。  
对数处理后的NMSE一般在1.45~1.65，比不取对数也许有改善，但也不是很大。将NMSE改成用其他指标（e.g. median）计算，效果也不明显。  
回归后根据变量重要性，共筛选出13个基因：Gene 13, 14, 34, 44, 62, 72, 77, 88, 94, 171, 195, 214, 260.  
基本和不取对数时一致（由于随机森林回归也具有一定随机性，每次结果不完全相同，这是综合多次的结果来说的）。  